/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AttendanceStatus = IDL.Variant({
  'present' : IDL.Null,
  'absent' : IDL.Null,
});
export const TeacherId = IDL.Nat;
export const AttendanceInput = IDL.Record({
  'status' : AttendanceStatus,
  'date' : IDL.Text,
  'notes' : IDL.Text,
  'teacherId' : TeacherId,
});
export const AttendanceId = IDL.Nat;
export const StudentId = IDL.Nat;
export const FeePaymentInput = IDL.Record({
  'month' : IDL.Nat,
  'activityPaid' : IDL.Nat,
  'studentId' : StudentId,
  'year' : IDL.Nat,
  'totalDue' : IDL.Nat,
  'otherPaid' : IDL.Nat,
  'paymentDate' : IDL.Text,
  'tuitionPaid' : IDL.Nat,
  'transportPaid' : IDL.Nat,
});
export const PaymentId = IDL.Nat;
export const FeeStructureInput = IDL.Record({
  'tuitionFee' : IDL.Nat,
  'activityFee' : IDL.Nat,
  'otherFee' : IDL.Nat,
  'classGrade' : IDL.Text,
  'transportFee' : IDL.Nat,
  'effectiveFrom' : IDL.Text,
});
export const FeeStructureId = IDL.Nat;
export const SiblingGroupId = IDL.Nat;
export const StudentInput = IDL.Record({
  'dob' : IDL.Text,
  'parentEmail' : IDL.Text,
  'parentContact' : IDL.Text,
  'name' : IDL.Text,
  'siblingGroupId' : IDL.Opt(SiblingGroupId),
  'rollNumber' : IDL.Text,
  'address' : IDL.Text,
  'classGrade' : IDL.Text,
  'parentName' : IDL.Text,
});
export const TeacherInput = IDL.Record({
  'subject' : IDL.Text,
  'name' : IDL.Text,
  'classAssigned' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const Attendance = IDL.Record({
  'id' : AttendanceId,
  'status' : AttendanceStatus,
  'date' : IDL.Text,
  'createdAt' : Timestamp,
  'notes' : IDL.Text,
  'teacherId' : TeacherId,
});
export const FeePayment = IDL.Record({
  'id' : PaymentId,
  'month' : IDL.Nat,
  'activityPaid' : IDL.Nat,
  'studentId' : StudentId,
  'balance' : IDL.Nat,
  'createdAt' : Timestamp,
  'year' : IDL.Nat,
  'totalPaid' : IDL.Nat,
  'totalDue' : IDL.Nat,
  'otherPaid' : IDL.Nat,
  'paymentDate' : IDL.Text,
  'tuitionPaid' : IDL.Nat,
  'transportPaid' : IDL.Nat,
  'receiptNumber' : IDL.Text,
});
export const FeeStructure = IDL.Record({
  'id' : FeeStructureId,
  'tuitionFee' : IDL.Nat,
  'activityFee' : IDL.Nat,
  'otherFee' : IDL.Nat,
  'classGrade' : IDL.Text,
  'transportFee' : IDL.Nat,
  'effectiveFrom' : IDL.Text,
});
export const Student = IDL.Record({
  'id' : StudentId,
  'dob' : IDL.Text,
  'parentEmail' : IDL.Text,
  'parentContact' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'siblingGroupId' : IDL.Opt(SiblingGroupId),
  'rollNumber' : IDL.Text,
  'address' : IDL.Text,
  'classGrade' : IDL.Text,
  'parentName' : IDL.Text,
});
export const Teacher = IDL.Record({
  'id' : TeacherId,
  'subject' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'classAssigned' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addAttendance' : IDL.Func([AttendanceInput], [AttendanceId], []),
  'addFeePayment' : IDL.Func([FeePaymentInput], [PaymentId], []),
  'addFeeStructure' : IDL.Func([FeeStructureInput], [FeeStructureId], []),
  'addStudent' : IDL.Func([StudentInput], [StudentId], []),
  'addTeacher' : IDL.Func([TeacherInput], [TeacherId], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteAttendance' : IDL.Func([AttendanceId], [IDL.Bool], []),
  'deleteFeePayment' : IDL.Func([PaymentId], [IDL.Bool], []),
  'deleteFeeStructure' : IDL.Func([FeeStructureId], [IDL.Bool], []),
  'deleteStudent' : IDL.Func([StudentId], [IDL.Bool], []),
  'deleteTeacher' : IDL.Func([TeacherId], [IDL.Bool], []),
  'getAttendance' : IDL.Func([AttendanceId], [IDL.Opt(Attendance)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFeePayment' : IDL.Func([PaymentId], [IDL.Opt(FeePayment)], ['query']),
  'getFeeStructure' : IDL.Func(
      [FeeStructureId],
      [IDL.Opt(FeeStructure)],
      ['query'],
    ),
  'getFeeStructureByClass' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(FeeStructure)],
      ['query'],
    ),
  'getReceiptData' : IDL.Func([PaymentId], [IDL.Opt(FeePayment)], ['query']),
  'getSiblingGroupFeeTotal' : IDL.Func(
      [SiblingGroupId, IDL.Nat, IDL.Nat],
      [IDL.Nat],
      ['query'],
    ),
  'getStudent' : IDL.Func([StudentId], [IDL.Opt(Student)], ['query']),
  'getTeacher' : IDL.Func([TeacherId], [IDL.Opt(Teacher)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAttendances' : IDL.Func([], [IDL.Vec(Attendance)], ['query']),
  'listAttendancesByDate' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Attendance)],
      ['query'],
    ),
  'listAttendancesByTeacher' : IDL.Func(
      [TeacherId],
      [IDL.Vec(Attendance)],
      ['query'],
    ),
  'listFeePayments' : IDL.Func([], [IDL.Vec(FeePayment)], ['query']),
  'listFeePaymentsByStudent' : IDL.Func(
      [StudentId],
      [IDL.Vec(FeePayment)],
      ['query'],
    ),
  'listFeeStructures' : IDL.Func([], [IDL.Vec(FeeStructure)], ['query']),
  'listStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
  'listStudentsByClass' : IDL.Func([IDL.Text], [IDL.Vec(Student)], ['query']),
  'listStudentsByParentContact' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Student)],
      ['query'],
    ),
  'listStudentsBySiblingGroup' : IDL.Func(
      [SiblingGroupId],
      [IDL.Vec(Student)],
      ['query'],
    ),
  'listTeachers' : IDL.Func([], [IDL.Vec(Teacher)], ['query']),
  'searchStudents' : IDL.Func([IDL.Text], [IDL.Vec(Student)], ['query']),
  'updateAttendance' : IDL.Func(
      [AttendanceId, AttendanceInput],
      [IDL.Bool],
      [],
    ),
  'updateFeePayment' : IDL.Func([PaymentId, FeePaymentInput], [IDL.Bool], []),
  'updateFeeStructure' : IDL.Func(
      [FeeStructureId, FeeStructureInput],
      [IDL.Bool],
      [],
    ),
  'updateStudent' : IDL.Func([StudentId, StudentInput], [IDL.Bool], []),
  'updateTeacher' : IDL.Func([TeacherId, TeacherInput], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AttendanceStatus = IDL.Variant({
    'present' : IDL.Null,
    'absent' : IDL.Null,
  });
  const TeacherId = IDL.Nat;
  const AttendanceInput = IDL.Record({
    'status' : AttendanceStatus,
    'date' : IDL.Text,
    'notes' : IDL.Text,
    'teacherId' : TeacherId,
  });
  const AttendanceId = IDL.Nat;
  const StudentId = IDL.Nat;
  const FeePaymentInput = IDL.Record({
    'month' : IDL.Nat,
    'activityPaid' : IDL.Nat,
    'studentId' : StudentId,
    'year' : IDL.Nat,
    'totalDue' : IDL.Nat,
    'otherPaid' : IDL.Nat,
    'paymentDate' : IDL.Text,
    'tuitionPaid' : IDL.Nat,
    'transportPaid' : IDL.Nat,
  });
  const PaymentId = IDL.Nat;
  const FeeStructureInput = IDL.Record({
    'tuitionFee' : IDL.Nat,
    'activityFee' : IDL.Nat,
    'otherFee' : IDL.Nat,
    'classGrade' : IDL.Text,
    'transportFee' : IDL.Nat,
    'effectiveFrom' : IDL.Text,
  });
  const FeeStructureId = IDL.Nat;
  const SiblingGroupId = IDL.Nat;
  const StudentInput = IDL.Record({
    'dob' : IDL.Text,
    'parentEmail' : IDL.Text,
    'parentContact' : IDL.Text,
    'name' : IDL.Text,
    'siblingGroupId' : IDL.Opt(SiblingGroupId),
    'rollNumber' : IDL.Text,
    'address' : IDL.Text,
    'classGrade' : IDL.Text,
    'parentName' : IDL.Text,
  });
  const TeacherInput = IDL.Record({
    'subject' : IDL.Text,
    'name' : IDL.Text,
    'classAssigned' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const Attendance = IDL.Record({
    'id' : AttendanceId,
    'status' : AttendanceStatus,
    'date' : IDL.Text,
    'createdAt' : Timestamp,
    'notes' : IDL.Text,
    'teacherId' : TeacherId,
  });
  const FeePayment = IDL.Record({
    'id' : PaymentId,
    'month' : IDL.Nat,
    'activityPaid' : IDL.Nat,
    'studentId' : StudentId,
    'balance' : IDL.Nat,
    'createdAt' : Timestamp,
    'year' : IDL.Nat,
    'totalPaid' : IDL.Nat,
    'totalDue' : IDL.Nat,
    'otherPaid' : IDL.Nat,
    'paymentDate' : IDL.Text,
    'tuitionPaid' : IDL.Nat,
    'transportPaid' : IDL.Nat,
    'receiptNumber' : IDL.Text,
  });
  const FeeStructure = IDL.Record({
    'id' : FeeStructureId,
    'tuitionFee' : IDL.Nat,
    'activityFee' : IDL.Nat,
    'otherFee' : IDL.Nat,
    'classGrade' : IDL.Text,
    'transportFee' : IDL.Nat,
    'effectiveFrom' : IDL.Text,
  });
  const Student = IDL.Record({
    'id' : StudentId,
    'dob' : IDL.Text,
    'parentEmail' : IDL.Text,
    'parentContact' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'siblingGroupId' : IDL.Opt(SiblingGroupId),
    'rollNumber' : IDL.Text,
    'address' : IDL.Text,
    'classGrade' : IDL.Text,
    'parentName' : IDL.Text,
  });
  const Teacher = IDL.Record({
    'id' : TeacherId,
    'subject' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'classAssigned' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addAttendance' : IDL.Func([AttendanceInput], [AttendanceId], []),
    'addFeePayment' : IDL.Func([FeePaymentInput], [PaymentId], []),
    'addFeeStructure' : IDL.Func([FeeStructureInput], [FeeStructureId], []),
    'addStudent' : IDL.Func([StudentInput], [StudentId], []),
    'addTeacher' : IDL.Func([TeacherInput], [TeacherId], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteAttendance' : IDL.Func([AttendanceId], [IDL.Bool], []),
    'deleteFeePayment' : IDL.Func([PaymentId], [IDL.Bool], []),
    'deleteFeeStructure' : IDL.Func([FeeStructureId], [IDL.Bool], []),
    'deleteStudent' : IDL.Func([StudentId], [IDL.Bool], []),
    'deleteTeacher' : IDL.Func([TeacherId], [IDL.Bool], []),
    'getAttendance' : IDL.Func(
        [AttendanceId],
        [IDL.Opt(Attendance)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFeePayment' : IDL.Func([PaymentId], [IDL.Opt(FeePayment)], ['query']),
    'getFeeStructure' : IDL.Func(
        [FeeStructureId],
        [IDL.Opt(FeeStructure)],
        ['query'],
      ),
    'getFeeStructureByClass' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(FeeStructure)],
        ['query'],
      ),
    'getReceiptData' : IDL.Func([PaymentId], [IDL.Opt(FeePayment)], ['query']),
    'getSiblingGroupFeeTotal' : IDL.Func(
        [SiblingGroupId, IDL.Nat, IDL.Nat],
        [IDL.Nat],
        ['query'],
      ),
    'getStudent' : IDL.Func([StudentId], [IDL.Opt(Student)], ['query']),
    'getTeacher' : IDL.Func([TeacherId], [IDL.Opt(Teacher)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAttendances' : IDL.Func([], [IDL.Vec(Attendance)], ['query']),
    'listAttendancesByDate' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Attendance)],
        ['query'],
      ),
    'listAttendancesByTeacher' : IDL.Func(
        [TeacherId],
        [IDL.Vec(Attendance)],
        ['query'],
      ),
    'listFeePayments' : IDL.Func([], [IDL.Vec(FeePayment)], ['query']),
    'listFeePaymentsByStudent' : IDL.Func(
        [StudentId],
        [IDL.Vec(FeePayment)],
        ['query'],
      ),
    'listFeeStructures' : IDL.Func([], [IDL.Vec(FeeStructure)], ['query']),
    'listStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
    'listStudentsByClass' : IDL.Func([IDL.Text], [IDL.Vec(Student)], ['query']),
    'listStudentsByParentContact' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Student)],
        ['query'],
      ),
    'listStudentsBySiblingGroup' : IDL.Func(
        [SiblingGroupId],
        [IDL.Vec(Student)],
        ['query'],
      ),
    'listTeachers' : IDL.Func([], [IDL.Vec(Teacher)], ['query']),
    'searchStudents' : IDL.Func([IDL.Text], [IDL.Vec(Student)], ['query']),
    'updateAttendance' : IDL.Func(
        [AttendanceId, AttendanceInput],
        [IDL.Bool],
        [],
      ),
    'updateFeePayment' : IDL.Func([PaymentId, FeePaymentInput], [IDL.Bool], []),
    'updateFeeStructure' : IDL.Func(
        [FeeStructureId, FeeStructureInput],
        [IDL.Bool],
        [],
      ),
    'updateStudent' : IDL.Func([StudentId, StudentInput], [IDL.Bool], []),
    'updateTeacher' : IDL.Func([TeacherId, TeacherInput], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };