/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Attendance {
  'id' : AttendanceId,
  'status' : AttendanceStatus,
  'date' : string,
  'createdAt' : Timestamp,
  'notes' : string,
  'teacherId' : TeacherId,
}
export type AttendanceId = bigint;
export interface AttendanceInput {
  'status' : AttendanceStatus,
  'date' : string,
  'notes' : string,
  'teacherId' : TeacherId,
}
export type AttendanceStatus = { 'present' : null } |
  { 'absent' : null };
export interface FeePayment {
  'id' : PaymentId,
  'month' : bigint,
  'activityPaid' : bigint,
  'studentId' : StudentId,
  'balance' : bigint,
  'createdAt' : Timestamp,
  'year' : bigint,
  'totalPaid' : bigint,
  'totalDue' : bigint,
  'otherPaid' : bigint,
  'paymentDate' : string,
  'tuitionPaid' : bigint,
  'transportPaid' : bigint,
  'receiptNumber' : string,
}
export interface FeePaymentInput {
  'month' : bigint,
  'activityPaid' : bigint,
  'studentId' : StudentId,
  'year' : bigint,
  'totalDue' : bigint,
  'otherPaid' : bigint,
  'paymentDate' : string,
  'tuitionPaid' : bigint,
  'transportPaid' : bigint,
}
export interface FeeStructure {
  'id' : FeeStructureId,
  'tuitionFee' : bigint,
  'activityFee' : bigint,
  'otherFee' : bigint,
  'classGrade' : string,
  'transportFee' : bigint,
  'effectiveFrom' : string,
}
export type FeeStructureId = bigint;
export interface FeeStructureInput {
  'tuitionFee' : bigint,
  'activityFee' : bigint,
  'otherFee' : bigint,
  'classGrade' : string,
  'transportFee' : bigint,
  'effectiveFrom' : string,
}
export type PaymentId = bigint;
export type SiblingGroupId = bigint;
export interface Student {
  'id' : StudentId,
  'dob' : string,
  'parentEmail' : string,
  'parentContact' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'siblingGroupId' : [] | [SiblingGroupId],
  'rollNumber' : string,
  'address' : string,
  'classGrade' : string,
  'parentName' : string,
}
export type StudentId = bigint;
export interface StudentInput {
  'dob' : string,
  'parentEmail' : string,
  'parentContact' : string,
  'name' : string,
  'siblingGroupId' : [] | [SiblingGroupId],
  'rollNumber' : string,
  'address' : string,
  'classGrade' : string,
  'parentName' : string,
}
export interface Teacher {
  'id' : TeacherId,
  'subject' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'classAssigned' : string,
}
export type TeacherId = bigint;
export interface TeacherInput {
  'subject' : string,
  'name' : string,
  'classAssigned' : string,
}
export type Timestamp = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addAttendance' : ActorMethod<[AttendanceInput], AttendanceId>,
  'addFeePayment' : ActorMethod<[FeePaymentInput], PaymentId>,
  'addFeeStructure' : ActorMethod<[FeeStructureInput], FeeStructureId>,
  'addStudent' : ActorMethod<[StudentInput], StudentId>,
  'addTeacher' : ActorMethod<[TeacherInput], TeacherId>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteAttendance' : ActorMethod<[AttendanceId], boolean>,
  'deleteFeePayment' : ActorMethod<[PaymentId], boolean>,
  'deleteFeeStructure' : ActorMethod<[FeeStructureId], boolean>,
  'deleteStudent' : ActorMethod<[StudentId], boolean>,
  'deleteTeacher' : ActorMethod<[TeacherId], boolean>,
  'getAttendance' : ActorMethod<[AttendanceId], [] | [Attendance]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFeePayment' : ActorMethod<[PaymentId], [] | [FeePayment]>,
  'getFeeStructure' : ActorMethod<[FeeStructureId], [] | [FeeStructure]>,
  'getFeeStructureByClass' : ActorMethod<[string], [] | [FeeStructure]>,
  'getReceiptData' : ActorMethod<[PaymentId], [] | [FeePayment]>,
  'getSiblingGroupFeeTotal' : ActorMethod<
    [SiblingGroupId, bigint, bigint],
    bigint
  >,
  'getStudent' : ActorMethod<[StudentId], [] | [Student]>,
  'getTeacher' : ActorMethod<[TeacherId], [] | [Teacher]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAttendances' : ActorMethod<[], Array<Attendance>>,
  'listAttendancesByDate' : ActorMethod<[string], Array<Attendance>>,
  'listAttendancesByTeacher' : ActorMethod<[TeacherId], Array<Attendance>>,
  'listFeePayments' : ActorMethod<[], Array<FeePayment>>,
  'listFeePaymentsByStudent' : ActorMethod<[StudentId], Array<FeePayment>>,
  'listFeeStructures' : ActorMethod<[], Array<FeeStructure>>,
  'listStudents' : ActorMethod<[], Array<Student>>,
  'listStudentsByClass' : ActorMethod<[string], Array<Student>>,
  'listStudentsByParentContact' : ActorMethod<[string], Array<Student>>,
  'listStudentsBySiblingGroup' : ActorMethod<[SiblingGroupId], Array<Student>>,
  'listTeachers' : ActorMethod<[], Array<Teacher>>,
  'searchStudents' : ActorMethod<[string], Array<Student>>,
  'updateAttendance' : ActorMethod<[AttendanceId, AttendanceInput], boolean>,
  'updateFeePayment' : ActorMethod<[PaymentId, FeePaymentInput], boolean>,
  'updateFeeStructure' : ActorMethod<
    [FeeStructureId, FeeStructureInput],
    boolean
  >,
  'updateStudent' : ActorMethod<[StudentId, StudentInput], boolean>,
  'updateTeacher' : ActorMethod<[TeacherId, TeacherInput], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];