/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TeacherInput {
    subject: string;
    name: string;
    classAssigned: string;
}
export type Timestamp = bigint;
export interface Attendance {
    id: AttendanceId;
    status: AttendanceStatus;
    date: string;
    createdAt: Timestamp;
    notes: string;
    teacherId: TeacherId;
}
export interface StudentInput {
    dob: string;
    parentEmail: string;
    parentContact: string;
    name: string;
    siblingGroupId?: SiblingGroupId;
    rollNumber: string;
    address: string;
    classGrade: string;
    parentName: string;
}
export type FeeStructureId = bigint;
export interface Teacher {
    id: TeacherId;
    subject: string;
    name: string;
    createdAt: Timestamp;
    classAssigned: string;
}
export type StudentId = bigint;
export type TeacherId = bigint;
export interface FeeStructure {
    id: FeeStructureId;
    tuitionFee: bigint;
    activityFee: bigint;
    otherFee: bigint;
    classGrade: string;
    transportFee: bigint;
    effectiveFrom: string;
}
export type SiblingGroupId = bigint;
export interface FeePayment {
    id: PaymentId;
    month: bigint;
    activityPaid: bigint;
    studentId: StudentId;
    balance: bigint;
    createdAt: Timestamp;
    year: bigint;
    totalPaid: bigint;
    totalDue: bigint;
    otherPaid: bigint;
    paymentDate: string;
    tuitionPaid: bigint;
    transportPaid: bigint;
    receiptNumber: string;
}
export type AttendanceId = bigint;
export type PaymentId = bigint;
export interface AttendanceInput {
    status: AttendanceStatus;
    date: string;
    notes: string;
    teacherId: TeacherId;
}
export interface FeeStructureInput {
    tuitionFee: bigint;
    activityFee: bigint;
    otherFee: bigint;
    classGrade: string;
    transportFee: bigint;
    effectiveFrom: string;
}
export interface FeePaymentInput {
    month: bigint;
    activityPaid: bigint;
    studentId: StudentId;
    year: bigint;
    totalDue: bigint;
    otherPaid: bigint;
    paymentDate: string;
    tuitionPaid: bigint;
    transportPaid: bigint;
}
export interface Student {
    id: StudentId;
    dob: string;
    parentEmail: string;
    parentContact: string;
    name: string;
    createdAt: Timestamp;
    siblingGroupId?: SiblingGroupId;
    rollNumber: string;
    address: string;
    classGrade: string;
    parentName: string;
}
export enum AttendanceStatus {
    present = "present",
    absent = "absent"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControl(): Promise<void>;
    addAttendance(input: AttendanceInput): Promise<AttendanceId>;
    addFeePayment(input: FeePaymentInput): Promise<PaymentId>;
    addFeeStructure(input: FeeStructureInput): Promise<FeeStructureId>;
    addStudent(input: StudentInput): Promise<StudentId>;
    addTeacher(input: TeacherInput): Promise<TeacherId>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteAttendance(id: AttendanceId): Promise<boolean>;
    deleteFeePayment(id: PaymentId): Promise<boolean>;
    deleteFeeStructure(id: FeeStructureId): Promise<boolean>;
    deleteStudent(id: StudentId): Promise<boolean>;
    deleteTeacher(id: TeacherId): Promise<boolean>;
    getAttendance(id: AttendanceId): Promise<Attendance | null>;
    getCallerUserRole(): Promise<UserRole>;
    getFeePayment(id: PaymentId): Promise<FeePayment | null>;
    getFeeStructure(id: FeeStructureId): Promise<FeeStructure | null>;
    getFeeStructureByClass(classGrade: string): Promise<FeeStructure | null>;
    getReceiptData(id: PaymentId): Promise<FeePayment | null>;
    getSiblingGroupFeeTotal(siblingGroupId: SiblingGroupId, _month: bigint, _year: bigint): Promise<bigint>;
    getStudent(id: StudentId): Promise<Student | null>;
    getTeacher(id: TeacherId): Promise<Teacher | null>;
    isCallerAdmin(): Promise<boolean>;
    listAttendances(): Promise<Array<Attendance>>;
    listAttendancesByDate(date: string): Promise<Array<Attendance>>;
    listAttendancesByTeacher(teacherId: TeacherId): Promise<Array<Attendance>>;
    listFeePayments(): Promise<Array<FeePayment>>;
    listFeePaymentsByStudent(studentId: StudentId): Promise<Array<FeePayment>>;
    listFeeStructures(): Promise<Array<FeeStructure>>;
    listStudents(): Promise<Array<Student>>;
    listStudentsByClass(classGrade: string): Promise<Array<Student>>;
    listStudentsByParentContact(contact: string): Promise<Array<Student>>;
    listStudentsBySiblingGroup(siblingGroupId: SiblingGroupId): Promise<Array<Student>>;
    listTeachers(): Promise<Array<Teacher>>;
    searchStudents(term: string): Promise<Array<Student>>;
    updateAttendance(id: AttendanceId, input: AttendanceInput): Promise<boolean>;
    updateFeePayment(id: PaymentId, input: FeePaymentInput): Promise<boolean>;
    updateFeeStructure(id: FeeStructureId, input: FeeStructureInput): Promise<boolean>;
    updateStudent(id: StudentId, input: StudentInput): Promise<boolean>;
    updateTeacher(id: TeacherId, input: TeacherInput): Promise<boolean>;
}
import type { Attendance as _Attendance, AttendanceId as _AttendanceId, AttendanceInput as _AttendanceInput, AttendanceStatus as _AttendanceStatus, FeePayment as _FeePayment, FeeStructure as _FeeStructure, SiblingGroupId as _SiblingGroupId, Student as _Student, StudentId as _StudentId, StudentInput as _StudentInput, Teacher as _Teacher, TeacherId as _TeacherId, Timestamp as _Timestamp, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async addAttendance(arg0: AttendanceInput): Promise<AttendanceId> {
        if (this.processError) {
            try {
                const result = await this.actor.addAttendance(to_candid_AttendanceInput_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAttendance(to_candid_AttendanceInput_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addFeePayment(arg0: FeePaymentInput): Promise<PaymentId> {
        if (this.processError) {
            try {
                const result = await this.actor.addFeePayment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFeePayment(arg0);
            return result;
        }
    }
    async addFeeStructure(arg0: FeeStructureInput): Promise<FeeStructureId> {
        if (this.processError) {
            try {
                const result = await this.actor.addFeeStructure(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFeeStructure(arg0);
            return result;
        }
    }
    async addStudent(arg0: StudentInput): Promise<StudentId> {
        if (this.processError) {
            try {
                const result = await this.actor.addStudent(to_candid_StudentInput_n5(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addStudent(to_candid_StudentInput_n5(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addTeacher(arg0: TeacherInput): Promise<TeacherId> {
        if (this.processError) {
            try {
                const result = await this.actor.addTeacher(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTeacher(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n7(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n7(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteAttendance(arg0: AttendanceId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAttendance(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAttendance(arg0);
            return result;
        }
    }
    async deleteFeePayment(arg0: PaymentId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFeePayment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFeePayment(arg0);
            return result;
        }
    }
    async deleteFeeStructure(arg0: FeeStructureId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFeeStructure(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFeeStructure(arg0);
            return result;
        }
    }
    async deleteStudent(arg0: StudentId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStudent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStudent(arg0);
            return result;
        }
    }
    async deleteTeacher(arg0: TeacherId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTeacher(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTeacher(arg0);
            return result;
        }
    }
    async getAttendance(arg0: AttendanceId): Promise<Attendance | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAttendance(arg0);
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAttendance(arg0);
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFeePayment(arg0: PaymentId): Promise<FeePayment | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeePayment(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeePayment(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFeeStructure(arg0: FeeStructureId): Promise<FeeStructure | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeeStructure(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeeStructure(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFeeStructureByClass(arg0: string): Promise<FeeStructure | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeeStructureByClass(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeeStructureByClass(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReceiptData(arg0: PaymentId): Promise<FeePayment | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getReceiptData(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReceiptData(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSiblingGroupFeeTotal(arg0: SiblingGroupId, arg1: bigint, arg2: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getSiblingGroupFeeTotal(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSiblingGroupFeeTotal(arg0, arg1, arg2);
            return result;
        }
    }
    async getStudent(arg0: StudentId): Promise<Student | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudent(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudent(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTeacher(arg0: TeacherId): Promise<Teacher | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTeacher(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTeacher(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listAttendances(): Promise<Array<Attendance>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAttendances();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAttendances();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAttendancesByDate(arg0: string): Promise<Array<Attendance>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAttendancesByDate(arg0);
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAttendancesByDate(arg0);
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAttendancesByTeacher(arg0: TeacherId): Promise<Array<Attendance>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAttendancesByTeacher(arg0);
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAttendancesByTeacher(arg0);
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async listFeePayments(): Promise<Array<FeePayment>> {
        if (this.processError) {
            try {
                const result = await this.actor.listFeePayments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listFeePayments();
            return result;
        }
    }
    async listFeePaymentsByStudent(arg0: StudentId): Promise<Array<FeePayment>> {
        if (this.processError) {
            try {
                const result = await this.actor.listFeePaymentsByStudent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listFeePaymentsByStudent(arg0);
            return result;
        }
    }
    async listFeeStructures(): Promise<Array<FeeStructure>> {
        if (this.processError) {
            try {
                const result = await this.actor.listFeeStructures();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listFeeStructures();
            return result;
        }
    }
    async listStudents(): Promise<Array<Student>> {
        if (this.processError) {
            try {
                const result = await this.actor.listStudents();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listStudents();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async listStudentsByClass(arg0: string): Promise<Array<Student>> {
        if (this.processError) {
            try {
                const result = await this.actor.listStudentsByClass(arg0);
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listStudentsByClass(arg0);
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async listStudentsByParentContact(arg0: string): Promise<Array<Student>> {
        if (this.processError) {
            try {
                const result = await this.actor.listStudentsByParentContact(arg0);
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listStudentsByParentContact(arg0);
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async listStudentsBySiblingGroup(arg0: SiblingGroupId): Promise<Array<Student>> {
        if (this.processError) {
            try {
                const result = await this.actor.listStudentsBySiblingGroup(arg0);
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listStudentsBySiblingGroup(arg0);
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async listTeachers(): Promise<Array<Teacher>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTeachers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTeachers();
            return result;
        }
    }
    async searchStudents(arg0: string): Promise<Array<Student>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchStudents(arg0);
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchStudents(arg0);
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateAttendance(arg0: AttendanceId, arg1: AttendanceInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAttendance(arg0, to_candid_AttendanceInput_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAttendance(arg0, to_candid_AttendanceInput_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateFeePayment(arg0: PaymentId, arg1: FeePaymentInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFeePayment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFeePayment(arg0, arg1);
            return result;
        }
    }
    async updateFeeStructure(arg0: FeeStructureId, arg1: FeeStructureInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFeeStructure(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFeeStructure(arg0, arg1);
            return result;
        }
    }
    async updateStudent(arg0: StudentId, arg1: StudentInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStudent(arg0, to_candid_StudentInput_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStudent(arg0, to_candid_StudentInput_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateTeacher(arg0: TeacherId, arg1: TeacherInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTeacher(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTeacher(arg0, arg1);
            return result;
        }
    }
}
function from_candid_AttendanceStatus_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AttendanceStatus): AttendanceStatus {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_Attendance_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Attendance): Attendance {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Student_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Student): Student {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FeePayment]): FeePayment | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FeeStructure]): FeeStructure | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Student]): Student | null {
    return value.length === 0 ? null : from_candid_Student_n19(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SiblingGroupId]): SiblingGroupId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Teacher]): Teacher | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Attendance]): Attendance | null {
    return value.length === 0 ? null : from_candid_Attendance_n10(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _AttendanceId;
    status: _AttendanceStatus;
    date: string;
    createdAt: _Timestamp;
    notes: string;
    teacherId: _TeacherId;
}): {
    id: AttendanceId;
    status: AttendanceStatus;
    date: string;
    createdAt: Timestamp;
    notes: string;
    teacherId: TeacherId;
} {
    return {
        id: value.id,
        status: from_candid_AttendanceStatus_n12(_uploadFile, _downloadFile, value.status),
        date: value.date,
        createdAt: value.createdAt,
        notes: value.notes,
        teacherId: value.teacherId
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _StudentId;
    dob: string;
    parentEmail: string;
    parentContact: string;
    name: string;
    createdAt: _Timestamp;
    siblingGroupId: [] | [_SiblingGroupId];
    rollNumber: string;
    address: string;
    classGrade: string;
    parentName: string;
}): {
    id: StudentId;
    dob: string;
    parentEmail: string;
    parentContact: string;
    name: string;
    createdAt: Timestamp;
    siblingGroupId?: SiblingGroupId;
    rollNumber: string;
    address: string;
    classGrade: string;
    parentName: string;
} {
    return {
        id: value.id,
        dob: value.dob,
        parentEmail: value.parentEmail,
        parentContact: value.parentContact,
        name: value.name,
        createdAt: value.createdAt,
        siblingGroupId: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.siblingGroupId)),
        rollNumber: value.rollNumber,
        address: value.address,
        classGrade: value.classGrade,
        parentName: value.parentName
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    present: null;
} | {
    absent: null;
}): AttendanceStatus {
    return "present" in value ? AttendanceStatus.present : "absent" in value ? AttendanceStatus.absent : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Attendance>): Array<Attendance> {
    return value.map((x)=>from_candid_Attendance_n10(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Student>): Array<Student> {
    return value.map((x)=>from_candid_Student_n19(_uploadFile, _downloadFile, x));
}
function to_candid_AttendanceInput_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AttendanceInput): _AttendanceInput {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_AttendanceStatus_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AttendanceStatus): _AttendanceStatus {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_StudentInput_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StudentInput): _StudentInput {
    return to_candid_record_n6(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: AttendanceStatus;
    date: string;
    notes: string;
    teacherId: TeacherId;
}): {
    status: _AttendanceStatus;
    date: string;
    notes: string;
    teacherId: _TeacherId;
} {
    return {
        status: to_candid_AttendanceStatus_n3(_uploadFile, _downloadFile, value.status),
        date: value.date,
        notes: value.notes,
        teacherId: value.teacherId
    };
}
function to_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dob: string;
    parentEmail: string;
    parentContact: string;
    name: string;
    siblingGroupId?: SiblingGroupId;
    rollNumber: string;
    address: string;
    classGrade: string;
    parentName: string;
}): {
    dob: string;
    parentEmail: string;
    parentContact: string;
    name: string;
    siblingGroupId: [] | [_SiblingGroupId];
    rollNumber: string;
    address: string;
    classGrade: string;
    parentName: string;
} {
    return {
        dob: value.dob,
        parentEmail: value.parentEmail,
        parentContact: value.parentContact,
        name: value.name,
        siblingGroupId: value.siblingGroupId ? candid_some(value.siblingGroupId) : candid_none(),
        rollNumber: value.rollNumber,
        address: value.address,
        classGrade: value.classGrade,
        parentName: value.parentName
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AttendanceStatus): {
    present: null;
} | {
    absent: null;
} {
    return value == AttendanceStatus.present ? {
        present: null
    } : value == AttendanceStatus.absent ? {
        absent: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
